[package]
name = "bpf-program-template"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "=1.11.1"
borsh = "0.9.1"
borsh-derive = "0.9.1"

[features]
test-bpf = []

[lib]
crate-type = ["cdylib", "lib"]
